sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sunfire1800/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunfire1800/docker-react npm run test -- --coverage
